# Generated by Django 2.2.19 on 2022-01-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211227_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
